# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0012_auto_20160912_1938'),
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorDetail', models.TextField()),
                ('dd', models.BooleanField(default=False)),
                ('ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ca.CAProfile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentBodyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentBodyDetail', models.TextField()),
                ('sbd', models.BooleanField(default=False)),
                ('ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ca.CAProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='ca',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
