# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0012_auto_20160912_1938'),
        ('task', '0002_auto_20160912_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directorDetail', models.BooleanField(default=False)),
                ('studentBodyDetail', models.BooleanField(default=False)),
                ('pageLike', models.BooleanField(default=False)),
                ('ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ca.CAProfile')),
            ],
        ),
    ]
