# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20160916_0057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbconnect',
            name='accessToken',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
