# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 20:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_remove_caprofile_college_address'),
        ('task', '0003_auto_20160916_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgotPass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=250)),
                ('ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ca.CAProfile')),
            ],
        ),
    ]
