# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatus',
            name='newtask',
            field=models.BooleanField(default=False),
        ),
    ]
