# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-09 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_forgotpass_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgotpass',
            name='ca',
        ),
        migrations.AlterField(
            model_name='key',
            name='confirmationKey',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='forgotPassKey',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='ForgotPass',
        ),
    ]
