# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_taskstatus_newtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskstatus',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='directordetail',
            name='dd',
        ),
        migrations.RemoveField(
            model_name='studentbodydetail',
            name='sbd',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
