# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-22 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_forgotpass_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='ca',
        ),
        migrations.DeleteModel(
            name='Key',
        ),
    ]
