# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_auto_20160922_2317'),
        ('task', '0005_auto_20160922_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forgotPassKey', models.CharField(max_length=250)),
                ('confirmationKey', models.CharField(max_length=250)),
                ('ca', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ca.CAProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='forgotpass',
            name='ca',
        ),
        migrations.DeleteModel(
            name='ForgotPass',
        ),
    ]
