# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-23 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20160923_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='confirmationKey',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='forgotPassKey',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
