# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-08 14:10
from __future__ import unicode_literals

import ca.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TechnexUser', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CAProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year', models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')])),
                ('mobile_number', models.BigIntegerField()),
                ('whatsapp_number', models.BigIntegerField()),
                ('college_address', models.TextField()),
                ('postal_address', models.TextField()),
                ('pincode', models.PositiveIntegerField()),
                ('profile_photo', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('college', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TechnexUser.College')),
            ],
        ),
        migrations.CreateModel(
            name='MassNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mass_message', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('ca', models.ManyToManyField(to='ca.CAProfile')),
                ('mark_read', models.ManyToManyField(related_name='mark_read', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(upload_to=ca.models.get_user_image_folder)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.CAProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('mark_read', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.CAProfile')),
            ],
        ),
    ]
