# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 17:54
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CAProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('year', models.IntegerField(blank=True, choices=[(1, b'First'), (2, b'Second'), (3, b'Third'), (4, b'Fourth'), (5, b'Fifth')], null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('whatsapp_number', models.BigIntegerField(null=True)),
                ('college_address', models.TextField(null=True)),
                ('postal_address', models.TextField(null=True)),
                ('profile_photo', models.TextField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('whyChooseYou', models.TextField(blank=True, null=True)),
                ('pastExp', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('collegeId', models.AutoField(primary_key=True, serialize=False)),
                ('collegeName', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='caprofile',
            name='college',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ca.College'),
        ),
    ]
