# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-15 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caprofile',
            name='college_address',
        ),
    ]
