# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-17 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_remove_caprofile_college_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='caprofile',
            name='pinCode',
            field=models.BigIntegerField(null=True),
        ),
    ]
