# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-11 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0002_remove_caprofile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='caprofile',
            name='pastExp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caprofile',
            name='whyChooseYou',
            field=models.TextField(blank=True, null=True),
        ),
    ]
