# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0003_auto_20160911_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caprofile',
            name='college_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='caprofile',
            name='mobile_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='caprofile',
            name='postal_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='caprofile',
            name='whatsapp_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='caprofile',
            name='year',
            field=models.IntegerField(choices=[(1, 'First'), (2, 'Second'), (3, 'Third'), (4, 'Fourth'), (5, 'Fifth')], null=True),
        ),
    ]
