# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0004_auto_20160922_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='caprofile',
            name='isChoosen',
            field=models.BooleanField(default=False),
        ),
    ]
