# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0006_auto_20160912_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='massnotification',
            name='mark_read',
            field=models.ManyToManyField(blank=True, null=True, related_name='mark_read', to='ca.CAProfile'),
        ),
    ]
