# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0008_auto_20160912_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskId', models.AutoField(primary_key=True, serialize=False)),
                ('taskName', models.CharField(max_length=50)),
                ('taskDescription', models.TextField()),
                ('deadLine', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('ca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.CAProfile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ca.Task')),
            ],
        ),
    ]
