# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-12 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ca', '0011_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='taskinstance',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='taskinstance',
            name='task',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TaskInstance',
        ),
    ]
